# Generated by Django 6.0.4 on 2026-05-04 15:19

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_alamat_lengkap_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notifikasi_aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('User', 'Pengguna Standar')], default='User', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tingkat_pendidikan',
            field=models.CharField(choices=[('Pelajar', 'Pelajar (SD / SMP / SMA / SMK)'), ('Mahasiswa', 'Mahasiswa (D3 / S1 / S2)')], default='Pelajar', max_length=15),
        ),
        migrations.CreateModel(
            name='SesiPerangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sistem_operasi', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('terakhir_aktif', models.DateTimeField(auto_now=True)),
                ('is_aktif', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
