# Generated by Django 6.0.4 on 2026-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_biometric_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesiperangkat',
            options={'verbose_name': 'Sesi Perangkat', 'verbose_name_plural': 'Sesi Perangkat'},
        ),
    ]
