# Generated by Django 6.0.4 on 2026-06-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_sesiperangkat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pengingat_aktif',
            field=models.BooleanField(default=True),
        ),
    ]
