# Generated by Django 6.0.4 on 2026-05-04 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_chat', models.CharField(default='Percakapan Baru', max_length=255)),
                ('context_summary', models.TextField(blank=True, help_text='Ringkasan konteks obrolan (Memory AI) untuk menghemat token', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dokumen_terkait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_dokumen', to='documents.dokumenmateri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesanChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(choices=[('User', 'Pengguna'), ('AI', 'EIO AI')], max_length=10)),
                ('isi_pesan', models.TextField()),
                ('waktu_kirim', models.DateTimeField(auto_now_add=True)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='chat.sesichat')),
            ],
        ),
    ]
