# Generated by Django 6.0.4 on 2026-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesanchat',
            options={'verbose_name': 'Pesan Chat', 'verbose_name_plural': 'Pesan Chat'},
        ),
        migrations.AlterModelOptions(
            name='sesichat',
            options={'verbose_name': 'Sesi Chat', 'verbose_name_plural': 'Sesi Chat'},
        ),
    ]
