# Generated by Django 6.0.4 on 2026-05-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_pesanchat_options_alter_sesichat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesanchat',
            options={'ordering': ['waktu_kirim'], 'verbose_name': 'Pesan Chat', 'verbose_name_plural': 'Pesan Chat'},
        ),
        migrations.AlterModelOptions(
            name='sesichat',
            options={'ordering': ['-diupdate_pada'], 'verbose_name': 'Sesi Chat', 'verbose_name_plural': 'Sesi Chat'},
        ),
    ]
