# Generated by Django 6.0.4 on 2026-05-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_modul', models.CharField(max_length=255)),
                ('deskripsi_singkat', models.CharField(blank=True, help_text='Teks kecil di UI, misal: Modul Pembelajaran & Evaluasi', max_length=255, null=True)),
                ('file_dokumen', models.FileField(upload_to='materi_dokumen/')),
                ('mime_type', models.CharField(blank=True, help_text='Merekam tipe asli: application/pdf, application/msword, dll', max_length=50, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Ukuran file dalam bytes', null=True)),
                ('is_processed_ai', models.BooleanField(default=False)),
                ('rangkuman_ai', models.TextField(blank=True, null=True)),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
