# Generated by Django 6.0.4 on 2026-05-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumenmateri',
            options={'verbose_name': 'Dokumen Materi', 'verbose_name_plural': 'Dokumen Materi'},
        ),
    ]
