# Generated by Django 6.0.4 on 2026-05-04 16:41

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_dokumenmateri_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenmateri',
            name='file_dokumen',
            field=models.FileField(upload_to='materi_dokumen/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'ppt', 'pptx'], message='Hanya file PDF, DOCX, PPT, atau PPTX yang diperbolehkan.'), documents.models.validate_file_size]),
        ),
    ]
