# Generated by Django 6.0.4 on 2026-05-04 16:47

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_dokumenmateri_file_dokumen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumenmateri',
            options={},
        ),
        migrations.AlterField(
            model_name='dokumenmateri',
            name='deskripsi_singkat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dokumenmateri',
            name='file_dokumen',
            field=models.FileField(upload_to='materi_dokumen/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'ppt', 'pptx']), documents.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='dokumenmateri',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokumenmateri',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
