# Generated by Django 6.0.4 on 2026-05-13 05:36

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_dokumenmateri_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenmateri',
            name='file_dokumen',
            field=models.FileField(help_text='Format yang diizinkan: PDF, DOC/DOCX, PPT/PPTX. Maksimal 10 MB.', upload_to='materi_dokumen/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx']), documents.models.validate_file_size]),
        ),
    ]
