# Generated by Django 6.0.4 on 2026-05-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tugas', models.CharField(max_length=255)),
                ('tenggat_waktu', models.DateTimeField()),
                ('tingkat_kesulitan', models.CharField(choices=[('Mudah', 'Mudah'), ('Sedang', 'Sedang'), ('Sulit', 'Sulit')], default='Sedang', max_length=10)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('lampiran_gambar', models.ImageField(blank=True, null=True, upload_to='tugas_lampiran/')),
                ('is_selesai', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
