# Generated by Django 6.0.4 on 2026-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tugas',
            options={'verbose_name': 'Tugas', 'verbose_name_plural': 'Tugas'},
        ),
    ]
