# Generated by Django 6.0.4 on 2026-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tugas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tugas',
            options={'ordering': ['tenggat_waktu'], 'verbose_name': 'Tugas', 'verbose_name_plural': 'Tugas'},
        ),
        migrations.AddField(
            model_name='tugas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
