# Generated by Django 6.0.4 on 2026-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tugas_options_tugas_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='is_pengingat_terkirim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tugas',
            name='waktu_pengingat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
