# Generated by Django 6.0.4 on 2026-05-04 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_latihan', models.CharField(choices=[('Flashcard', 'Flashcard Pintar'), ('MCQ', 'Pilihan Ganda'), ('Essay', 'Essay')], max_length=20)),
                ('jumlah_soal', models.IntegerField(default=10)),
                ('durasi_waktu_menit', models.IntegerField(blank=True, help_text='Durasi pengerjaan kuis dalam menit untuk timer UI', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latihan_dokumen', to='documents.dokumenmateri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_latihan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HasilLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_total', models.IntegerField(default=0, help_text='Nilai akhir skala 0-100')),
                ('jumlah_benar', models.IntegerField(default=0)),
                ('jumlah_salah', models.IntegerField(default=0)),
                ('waktu_pengerjaan_asli', models.DurationField(blank=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_hasil', to=settings.AUTH_USER_MODEL)),
                ('sesi_latihan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil', to='latihan.sesilatihan')),
            ],
        ),
        migrations.CreateModel(
            name='SoalEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('batas_kata', models.IntegerField(default=500, help_text='Batas maksimal kata untuk jawaban')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_essay', to='latihan.sesilatihan')),
            ],
        ),
        migrations.CreateModel(
            name='SoalFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisi_depan', models.TextField(help_text='Pertanyaan atau Terminologi')),
                ('sisi_belakang', models.TextField(help_text='Jawaban atau Penjelasan')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_flashcard', to='latihan.sesilatihan')),
            ],
        ),
        migrations.CreateModel(
            name='SoalMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_mcq', to='latihan.sesilatihan')),
            ],
        ),
    ]
