# Generated by Django 6.0.4 on 2026-05-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilihanMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=255)),
                ('is_benar', models.BooleanField(default=False)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='latihan.soalmcq')),
            ],
        ),
        migrations.CreateModel(
            name='RekamEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.TextField(blank=True, null=True)),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_essay', to='latihan.hasillatihan')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latihan.soalessay')),
            ],
        ),
        migrations.CreateModel(
            name='RekamFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ingat', models.BooleanField(default=False)),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_flashcard', to='latihan.hasillatihan')),
                ('kartu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latihan.soalflashcard')),
            ],
        ),
        migrations.CreateModel(
            name='RekamMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_mcq', to='latihan.hasillatihan')),
                ('pilihan_dipilih', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='latihan.pilihanmcq')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latihan.soalmcq')),
            ],
        ),
    ]
