# Generated by Django 6.0.4 on 2026-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0002_pilihanmcq_rekamessay_rekamflashcard_rekammcq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hasillatihan',
            options={'verbose_name': 'Hasil Latihan', 'verbose_name_plural': 'Hasil Latihan'},
        ),
        migrations.AlterModelOptions(
            name='rekamessay',
            options={'verbose_name': 'Rekam Essay', 'verbose_name_plural': 'Rekam Essay'},
        ),
        migrations.AlterModelOptions(
            name='rekamflashcard',
            options={'verbose_name': 'Rekam Flashcard', 'verbose_name_plural': 'Rekam Flashcard'},
        ),
        migrations.AlterModelOptions(
            name='rekammcq',
            options={'verbose_name': 'Rekam MCQ', 'verbose_name_plural': 'Rekam MCQ'},
        ),
        migrations.AlterModelOptions(
            name='sesilatihan',
            options={'verbose_name': 'Sesi Latihan', 'verbose_name_plural': 'Sesi Latihan'},
        ),
        migrations.AlterModelOptions(
            name='soalessay',
            options={'verbose_name': 'Soal Essay', 'verbose_name_plural': 'Soal Essay'},
        ),
        migrations.AlterModelOptions(
            name='soalflashcard',
            options={'verbose_name': 'Soal Flashcard', 'verbose_name_plural': 'Soal Flashcard'},
        ),
        migrations.AlterModelOptions(
            name='soalmcq',
            options={'verbose_name': 'Soal MCQ', 'verbose_name_plural': 'Soal MCQ'},
        ),
    ]
