# Generated by Django 6.0.4 on 2026-05-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0003_alter_hasillatihan_options_alter_rekamessay_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilihanmcq',
            options={'verbose_name': 'PilihanMCQ', 'verbose_name_plural': 'PilihanMCQ'},
        ),
    ]
