# Generated by Django 6.0.4 on 2026-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0004_alter_pilihanmcq_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekammcq',
            name='pilihan_dipilih',
        ),
        migrations.AddField(
            model_name='rekammcq',
            name='jawaban_user',
            field=models.CharField(blank=True, choices=[('A', 'Opsi A'), ('B', 'Opsi B'), ('C', 'Opsi C'), ('D', 'Opsi D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='soalmcq',
            name='jawaban_benar',
            field=models.CharField(blank=True, choices=[('A', 'Opsi A'), ('B', 'Opsi B'), ('C', 'Opsi C'), ('D', 'Opsi D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='soalmcq',
            name='opsi_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soalmcq',
            name='opsi_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soalmcq',
            name='opsi_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soalmcq',
            name='opsi_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
