# Generated by Django 6.0.4 on 2026-06-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0005_remove_rekammcq_pilihan_dipilih_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilihanmcq',
            options={'verbose_name': 'Pilihan MCQ', 'verbose_name_plural': 'Pilihan MCQ'},
        ),
    ]
